apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    tier: backend
    component: backend
    project: expense
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: backend
      component: backend
      project: expense 
  template:
    metadata:
      labels:
        tier: backend
        component: backend
        project: expense 
    spec:
      containers:
      - name: backend
        image: sky1ger/backend:v1.0
        envFrom:
          - configMapRef:
              name: backend
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    tier: backend
    component: backend
    project: expense 
  ports:
  - protocol: TCP
    port: 8080 #serviceport differs from target port
    targetPort: 8080